# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>
cyvcf2=0.11.6sp
impyla=0.16.1
lark-parser=0.6.7
matplotlib>=3.3.1
networkx=2.3
numpy>=1.16.4
pandas>=1.0.3
pyarrow=2.0.0
pyliftover>=0.4
pysam=0.15.4
pytest>=5.4.1
python>=3.7.5
python-box
samtools=1.9
scipy>=1.4.1
setuptools=46.1.3
sqlalchemy=1.3.15
sqlite>=3.29.0
statsmodels>=0.11.1
thriftpy2>=0.4.11
thrift>=0.13.0
django=2.2.8
django-cors-headers=3.2.1
django-guardian>=2.0.0
djangorestframework>=3.10.1
pytest-django>=3.9.0
coverage
flake8
pytest-cov
pytest-mock
pytest-xdist
pylint
seaborn
openjdk=8.0.192
hadoop=3.1.2
pybigwig>=0.3.17
deprecation=2.0.6
django-extensions=2.2.5
toml>=0.10.0
cerberus>=1.3.2
jinja2
pre-commit>=2.1.0
snakemake-minimal=5.20
ijson=3.1.3
mypy
lxml
bump2version
pytest-doctestplus=0.4.0
sphinx>=2.4.0
sphinx_rtd_theme
sphinx-copybutton
sphinxcontrib-httpdomain
beautifulsoup4
