# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>

name: gpf
channels:
  - conda-forge
  - bioconda
  - iossifovlab
dependencies:
  - versioneer=0.29
  - dask-kubernetes=2024.5
  - dask-jobqueue=0.8
  - coverage=7.5
  - ruff=0.4
  - mypy=1.10
  - pytest=8.2
  - pytest-cov=5.0
  - pytest-xdist=3.5
  - pytest-mock=3.14
  - pytest-django=4.8
  - pytest-doctestplus=1.2
  - pylint=3.2
  - pandas-stubs=2.1
  - django-stubs=5.0.2
  - types-pyyaml=6.0
  - types-setuptools=67
  - types-toml=0.10
  - types-python-dateutil=2.8
  - types-requests=2.27
  - invoke=2.2
  - gitpython=3.1
  - sphinx=7.3
  - sphinx_rtd_theme
  - sphinx-copybutton
  - sphinxcontrib-httpdomain
  - monkeytype
  - parquet-tools
  - pip
  - pip:
    - sphinx-autorun
    - rangehttpserver
    - sphinxcontrib-video
