# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
# conda create -c conda-forge -c bioconda -n <env name> --file <this file>

name: gpf
channels:
  - conda-forge
  - bioconda
  - iossifovlab
dependencies:
  - dask-kubernetes=2025.1.1
  - coverage
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-mock
  - pytest-django
  - pytest-doctestplus=1.2
  - ruff==0.14.6
  - pylint
  - nodejs>=24
  - mypy=1.15.0
  - flake8=7.1.1
  - pyarrow-stubs
  - pandas-stubs=2.1
  - django-stubs=5.2.2
  - types-pyyaml=6.0
  - types-setuptools=67
  - types-toml=0.10
  - types-python-dateutil=2.8
  - types-docker
  - types-psutil
  - invoke=2.2
  - gitpython=3.1
  - sphinx=7.3
  - sphinx_rtd_theme
  - sphinx-copybutton
  - sphinxcontrib-httpdomain
  - monkeytype
  - parquet-tools
  - ipython
  - curl
  - pip:
    - sphinx-autorun
    - sphinxcontrib-video
    - sphinx-last-updated-by-git
    - esbonio
    - doc8
    - rstcheck
    - types-requests-oauthlib
    - types-requests
    - types-psutil
